version: '3.8'

services:
  ids-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ids-system
    privileged: true  # 需要特权才能访问网络接口
    network_mode: "host"  # 使用主机网络模式以便于捕获流量
    volumes:
      - ../data:/app/data
    ports:
      - "5000:5000"  # Web界面端口
    restart: unless-stopped
    
  # 可选：添加一个MongoDB容器用于存储日志和攻击数据
  mongodb:
    image: mongo:4.4
    container_name: ids-mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data:
